### DISCUSSION TITLE
add hide_all for history + logbook

### DISCUSSION THREAD

**Discussion by Mariusthvdb** [Mariusthvdb/custom-more-info#3] [Ideas]
```
hide_all:

  by_domain:
    - number
```

like we have the `filter_all` in the attributes

**Comment by Mariusthvdb** [comment]
@elchininet did we ever look at this any further?

would be a very valuable option for the regular entities that dont have the header icon (which we can now hide directly)

**Comment by elchininet** [comment]
Try with the `all` boolean, it should work (the same way as the history icon)

**Reply by elchininet** [reply]
Now thinking about that, the current `all`  is an absolute all, it doesn't allow it to be granular. I will think about how to refactor it.

**Comment by Mariusthvdb** [comment]
> Try with the `all` boolean, it should work (the same way as the history icon)

please tell me how? I dont understand where the `all` option can be set

**Reply by elchininet** [reply]
Do not worry about it, I need to refactor it. There is no way to set it up to hide the option for certain domains or device classes, etc. It is like `kiosk-mode`, hide something completely.

```yaml
custom_more_info:
  ## The same with unhide_header_history_icon , hide_history, hide_logbook, unhide_history, and unhide_logbook 
  hide_header_history_icon:
    all: true
```

**Reply by Mariusthvdb** [reply]
just to be sure, what I meant to ask was whether we have an option to hide both the history And logbook sections with 1 config option

```
hide_all: # hide history And logbook

  by_domain:
    - number

  by_glob:
    - 'sensor.buienradar_*'
```
