### ISSUE TITLE
hide by_device_class: battery still shows history

### ISSUE THREAD

**Issue by Mariusthvdb** [Mariusthvdb/custom-more-info#13]
**Describe the bug**

even though hiding history And logbook from the `device_class: battery`, it still  shows it on the more-info panel

**Debug JSON from Inspector**
```
{
    "debug": true,
    "auto_hide_header_history_icon": true,
    "hide_header_history_icon": {
        "by_entity_id": [
            "sun.sun"
        ]
    },
    "hide_history_logbook": {
        "by_domain": [
            "alarm_control_panel",
            "alert",
            "automation",
            "button",
            "camera",
            "climate",
            "counter",
            "cover",
            "fan",
            "geo_location",
            "group",
            "image",
            "input_boolean",
            "input_button",
            "input_datetime",
            "input_number",
            "input_select",
            "input_text",
            "light",
            "media_player",
            "number",
            "proximity",
            "remote",
            "scene",
            "script",
            "select",
            "siren",
            "sun",
            "text",
            "timer",
            "update",
            "weather",
            "zone"
        ],
        "by_device_class": [
            "battery"
        ]
    },
    "hide_history": {
        "by_entity_id": [
            "binary_sensor.ongemeten_verbruik_te_hoog",
            "sensor.ha_main_config",
            "sensor.buienradar_iungo_winddirection",
            "sensor.buienradar_iungo_locatie"
        ],
        "by_device_class": [
            "sound",
            "battery"
        ],
        "by_glob": [
            "sensor.knmi*",
            "sensor.tomorrow*",
            "sensor.afvalwijzer*",
            "sensor.awair_element_*",
            "sensor.distance_*",
            "sensor.*_naar_huis_duration"
        ]
    },
```
**Custom-more-info Version:**
1.1.0

**To Reproduce**

**Expected behavior**
Hide History when set to hide

Ive even set it to hide on 
```
hide_history_logbook:
  by_device_class:
    - battery
```

and

```
hide_history:
  by_device_class:
    - battery
```

**Screenshots**

<img width="1687" alt="Scherm­afbeelding 2024-01-22 om 11 22 24" src="https://github.com/Mariusthvdb/custom-more-info/assets/33354141/59a3096d-55a2-42ba-8f33-3d9cf917865e">

**Dom Path of attributes dropdown box**
Always include screenshot to the path of the attributes that error
We cant help you without that exact info

<img width="1015" alt="Scherm­afbeelding 2024-01-22 om 11 26 25" src="https://github.com/Mariusthvdb/custom-more-info/assets/33354141/7aea8d8a-cb11-464f-b06b-eb1bca30fcc4">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**The custom-more-info configuration**
```yaml
debug: true
auto_hide_header_history_icon: true

hide_header_history_icon:

  by_entity_id:
    - sun.sun

hide_history_logbook:

  by_domain:
    - alarm_control_panel
    - alert
    - automation
  #  - binary_sensor
    - button
    - camera
    - climate
    - counter
    - cover
  #  - device_tracker
  #  - event
    - fan
    - geo_location
    - group
    - image
    - input_boolean
    - input_button
    - input_datetime
    - input_number
    - input_select
    - input_text
    - light
    - media_player
    - number
  #  - person
    - proximity
    - remote
    - scene
    - script
    - select
  #  - sensor
    - siren
    - sun
  #  - switch
    - text
    - timer
    - update
    - weather
    - zone

  by_device_class:
    - battery

hide_history:
  by_entity_id:
     - binary_sensor.ongemeten_verbruik_te_hoog
     - sensor.ha_main_config
     - sensor.buienradar_iungo_winddirection
     - sensor.buienradar_iungo_locatie

#   by_domain:
#     - input_select
#     - select
#     - input_boolean
#     - number
#     - input_number
#     - siren

  by_device_class:
    - sound
    - battery
```

**Additional context**
