### ISSUE TITLE
no cogwheel response: TypeError: null is not an object (evaluating 'n.cssRules')

### ISSUE THREAD

**Issue by Mariusthvdb** [Mariusthvdb/custom-more-info#14]
**Describe the bug**

when clicking the cogwheel to go to the settings of eg an input_select:

<img width="621" alt="Scherm­afbeelding 2024-01-31 om 13 18 45" src="https://github.com/Mariusthvdb/custom-more-info/assets/33354141/b5f77e6b-1107-4aab-970a-07c4a0210ec3">

the response is:

<img width="646" alt="Scherm­afbeelding 2024-01-31 om 13 18 52" src="https://github.com/Mariusthvdb/custom-more-info/assets/33354141/67cd72b4-2da8-47c5-a239-e69d125bc543">

which is somewhat unexplained, as custom-more-info does not hide the settings at all?
 

**Debug JSON from Inspector**
```
{
    "hide_history": true,
    "hide_logbook": true,
    "hide_header_history_icon": true
}
```
**Custom-more-info Version:**
1.1.0

**Expected behavior**

**Screenshots**

this is in inspector

<img width="1629" alt="Scherm­afbeelding 2024-01-31 om 13 34 13" src="https://github.com/Mariusthvdb/custom-more-info/assets/33354141/08bb3092-02e7-4dcd-aacd-5b72d72ec875">

**Dom Path of attributes dropdown box**
Always include screenshot to the path of the attributes that error
We cant help you without that exact info

<img width="989" alt="Scherm­afbeelding 2024-01-31 om 13 37 57" src="https://github.com/Mariusthvdb/custom-more-info/assets/33354141/0229c907-0c81-4323-bc09-25b5fa9304e9">

**Desktop (please complete the following information):**

**The custom-more-info configuration**
```yaml
##########################################################################################
# Custom attributes configuration settings                                               #
# use a config per Dashboard, and add it to the root of the yaml file like               #
#                                                                                        #
#      ############################################################################      #
#      # title: Your Dashboard title                                              #      #
#      #                                                                          #      #
#      # button_card_templates: !include_dir_merge_named ../button_card_templates #      #
#      # decluttering_templates: !include_dir_named ../decluttering_templates     #      #
#      # kiosk_mode: !include ../kiosk-mode/kiosk-mode.yaml                       #      #
#      # custom_attributes: !include ../custom_attributes/custom_attributes.yaml  #      #
#      #                                                                          #      #
#      # views:                                                                   #      #
#      #   - !include view_home.yaml                                              #      #
#      #   - !include view_number_two                                             #      #
#      #   - etc                                                                  #      #
#      ############################################################################      #
#                                                                                        #
##########################################################################################

# use the available 'debug' paramater if a filter does not work and you need to report
# malfunctioning to the issue tracker.

debug: true
auto_hide_header_history_icon: true

hide_header_history_icon:

  by_entity_id:
    - sun.sun

hide_history_logbook:

  by_domain:
    - alarm_control_panel
    - alert
    - automation
  #  - binary_sensor
    - button
    - camera
    - climate
    - counter
    - cover
  #  - device_tracker
  #  - event
    - fan
    - geo_location
    - group
    - image
    - input_boolean
    - input_button
    - input_datetime
    - input_number
    - input_select
    - input_text
    - light
    - media_player
    - number
  #  - person
    - proximity
    - remote
    - scene
    - script
    - select
  #  - sensor
    - siren
    - sun
  #  - switch
    - text
    - timer
    - update
    - weather
    - zone

#     by_entity_id:
#       -

  by_device_class:
    - battery
    - sound

#     by_glob:
#       -
#
# unhide_history_logbook:
#
#     by_entity_id:
#       -
#
#     by_domain:
#       -
#
#     by_device_class:
#       -
#
#     by_glob:
#       -

hide_history:
  by_entity_id:
     - binary_sensor.ongemeten_verbruik_te_hoog
     - sensor.ha_main_config
     - sensor.buienradar_iungo_winddirection
     - sensor.buienradar_iungo_locatie

#   by_domain:
#     - input_select
#     - select
#     - input_boolean
#     - number
#     - input_number
#     - siren

#   by_device_class:
#     - sound
#     - battery

  by_glob:
    - 'sensor.knmi*'
    - 'sensor.tomorrow*'
#     - 'siren.*'
#     - 'input_number.*'
    - 'sensor.afvalwijzer*'
    - 'sensor.awair_element_*'
    - 'sensor.distance_*'
    - 'sensor.*_naar_huis_duration'


unhide_history:

  by_entity_id:
    - sensor.tomorrow_cloud_cover
    - sensor.knmi_gevoelstemperatuur
    - sensor.awair_element_humidity
    - sensor.awair_element_carbon_dioxide

#   by_domain:
#     - some_domain
#     - some_domain
#
#   by_device_class:
#     - some_device_class
#     - some_device_class
#
#   by_glob:
#     - some_glob
#     - some_glob

hide_logbook:

  by_entity_id:
    - binary_sensor.ongemeten_verbruik_te_hoog
    - binary_sensor.power_using_off_switches

#   by_domain:
#     - input_select
#     - select
#     - input_boolean
#     - number
#     - device_tracker

  by_device_class:
    - sound

#   by_glob:
#     - '*_over*_detected'

# unhide_logbook:
#
#   by_entity_id:
#     - some_entity
#     - some_entity
#
#   by_domain:
#     - some_domain
#     - some_domain
#
#   by_device_class:
#     - some_device_class
#     - some_device_class
#
#   by_glob:
#     - some_glob
#     - some_glob

##########################################################################################
# Unfilter                                                                               #
##########################################################################################

#special boolean setting for all
# unfilter_all: true #/ false

unfilter_attributes:

  by_domain:

    zone:
      - persons

    device_tracker:
      - ip
      - mac
      - ap_mac

# # filtered by Home Assistant by default
#     binary_sensor:
#       - device_class
#
#     sensor:
#       - device_class

# filtered by User in the filter_attributes
  by_glob:

    'sensor.afvalwijzer*':
      - days_until_collection_date
      - is_collection_date_today
      - is_collection_date_tomorrow
      - is_collection_date_day_after_tomorrow

#     'device_tracker.google*':
#       - ip
#       - mac
#       - ap_mac

##########################################################################################
# Filter                                                                                 #
##########################################################################################

#special boolean setting for all
# filter_all: true

filter_attributes:

  by_glob:

    '*.*':
      - templates
      - icon_color
      - id

# filter all atributes on all entities
#       - all

# first filter 'all' in glob, then unfilter only what user needs in the unfilter section
#     'device_tracker.google*':
#       - all
#     'device_tracker.heater_*':
#       - all
#
#     'sensor.ha_*_version':
#       - all

    'sensor.buienradar_*':
      - Stationname

    'sensor.*_actueel': &meter # use a yaml anchor to easily c&p repetitive attributes
      - meter_type
      - meter_type_name

    'sensor.*_totaal': *meter

    'sensor.*_amperage': *meter

    'sensor.*_voltage': *meter

    'group.*trackers':
      - all

    'sensor.afvalwijzer*':
      - all

# test for custom-ui templates
#     'sensor.*_battery_state':
#       - templates

  by_device_class:

    enum:
      - options

    running: # used for threshold entities
      - all

  by_domain:

    zone:
      - all

    device_tracker:
      - all
#     binary_sensor:
#       - hysteresis

    light:
      - all

    siren:
      - available_tones

  by_entity_id:

    sensor.cpu_speed:
      - brand
      - arch

    sensor.schimmel_sensor:
      - all

    group.media_players_device_trackers:
      - all

    group.hub_device_trackers:
      - all
```

**Additional context**
Disabling custom-more-info brings it all back:

<img width="613" alt="Scherm­afbeelding 2024-01-31 om 13 43 41" src="https://github.com/Mariusthvdb/custom-more-info/assets/33354141/be8770cd-9d2c-4a87-ad16-1ea6bf68834b">

and settings:

<img width="613" alt="Scherm­afbeelding 2024-01-31 om 13 43 48" src="https://github.com/Mariusthvdb/custom-more-info/assets/33354141/b2a6ced4-df87-43f2-b762-cbf8af295f56">
