### ISSUE TITLE
hide_history_logbook: stopped working correctly 

### ISSUE THREAD

**Issue by Mariusthvdb** [Mariusthvdb/custom-more-info#18]
**Describe the bug**
quick note about missing functionality, need to find out if this is caused by changes in core frontend (currently running 2024.5.beta)

even though I have this set:
```
hide_history_logbook:

  by_domain:
    - alarm_control_panel
    - alert
    - automation
  #  - binary_sensor
    - button
    - camera
    - climate
    - counter
    - cover
  #  - device_tracker
  #  - event
    - fan
    - geo_location
    - group
    - image
    - input_boolean
    - input_button
    - input_datetime
    - input_number
    - input_select
    - input_text
    - light
    - media_player
    - number
  #  - person
    - remote
    - scene
    - script
    - select
  #  - sensor
    - siren
    - sun
  #  - switch
    - text
    - timer
    - update
    - weather
    - zone

  by_entity_id:
    - zone.efteling

  by_device_class:
    - battery
    - sound
```

we need to check if a) that is what we are supposed to do, and b) if you see the same?

device_class: setting the same to
```
  by_device_class:
    - battery
    - sound
```
 does work correctly, and only gives me the left over attribute I want.

a single entity_id:
```
  by_entity_id:
    - zone.efteling
```

 also still shows the history. 
Could it be the new frontend changed so we need to check the Dom?

hide logbook on a device_tracker  using:

```
hide_logbook:

  by_entity_id:
    - binary_sensor.ongemeten_verbruik_te_hoog
    - binary_sensor.power_using_off_switches

  by_domain:
    - device_tracker
```

also does Not work anymore ..
